# Generated by Django 3.2 on 2021-04-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210426_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
