# Generated by Django 3.2 on 2021-04-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_directory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filesection',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.file'),
        ),
    ]
