# Generated by Django 3.2 on 2021-04-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210428_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.statusdata'),
        ),
    ]
