# Generated by Django 3.2 on 2021-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210429_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncategory',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
